services:
    tatiana5.quickreply.listener:
        class: tatiana5\quickreply\event\listener
        arguments:
            - @auth
            - @config
            - @template
            - @user
            - @dbal.conn
            - @ext.manager
            - @request
            - @content.visibility
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }
