services:
    boardtools.quickreply.listener:
        class: boardtools\quickreply\event\listener
        arguments:
            - @auth
            - @config
            - @template
            - @user
            - @request
            - @boardtools.quickreply.listener_helper
        tags:
            - { name: event.listener }

    boardtools.quickreply.captcha_helper:
        class: boardtools\quickreply\functions\captcha_helper
        arguments:
            - @config
            - @template
            - @request
            - @captcha.factory

    boardtools.quickreply.ajax_helper:
        class: boardtools\quickreply\functions\ajax_helper
        arguments:
            - @auth
            - @config
            - @template
            - @user
            - @dbal.conn
            - @content.visibility
            - @request
            - %core.root_path%
            - %core.php_ext%

    boardtools.quickreply.form_helper:
        class: boardtools\quickreply\functions\form_helper
        arguments:
            - @auth
            - @config
            - @template
            - @user
            - @cache
            - @plupload
            - @mimetype.guesser
            - %core.root_path%
            - %core.php_ext%

    boardtools.quickreply.listener_helper:
        class: boardtools\quickreply\functions\listener_helper
        arguments:
            - @auth
            - @config
            - @template
            - @user
            - @ext.manager
            - @request
            - @boardtools.quickreply.ajax_helper
            - @boardtools.quickreply.captcha_helper
            - @boardtools.quickreply.form_helper
            - %core.root_path%
            - %core.php_ext%
